### PR TITLE
Remove jquery as dependency and refactor the code

### PR DESCRIPTION
**Pull request by luruke**
Hey, I've removed jquery as dependency (there's really no need of it!) and made a small refactoring of the code

### CODE REVIEW

**Comment by wilbertliu** [comment]
Hi luruke!

Thanks for the good work, this is awesome! 👏🏽
My question is, would changing jQuery into a plain JS lead to a significant performance improvement?

Thanks! 😉

**Comment by luruke** [comment]
Hey, for sure a plain js is much more faster than using jQuery :)
Also, since Mata is a chrome extension you don't need to deal and worry about old browsers and cross-browsers issues, where jquery is really helpful

**Comment by wilbertliu** [comment]
Aha, thank you for your explanation.
Will merge it soon! :+1:

**Comment by luruke** [comment]
Cool, probably it worth making some tests before

**Comment by wilbertliu** [comment]
Yeah, will test it manually first. Thanks man, you are awesome! :smile:

**Pull request merged**
